name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintProcessingSoftware:
    name: Print Node.js Version
    runs-on: ubuntu-latest
    steps:
      - name: Show Node.js Version
        run: node --version

  PrintDatabaseSoftware:
    name: Print MongoDB Version
    runs-on: ubuntu-latest
    needs: [PrintProcessingSoftware]
    steps:
      - name: Install MongoDB Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      - name: Show MongoDB Version
        run: mongod --version
